### ISSUE TITLE
Session ID is not transmitted on fetch when used within a servlet engine

### ISSUE THREAD

**Issue by rowe42** [arsnebula/nebula-i18n#1]
We are running a Polymer 2 application served from within a Tomcat application server (bundled within a Zuul Gateway), which is secured with OAuth2. This means that every request needs to send the Session ID so the request can be authenticated.
Now, the standard setting of fetch does NOT send Session-IDs, even if they exist (in form of a Session Cookie). In order to do so, one must add the setting `credentials: 'same-origin'`:
https://github.com/github/fetch#sending-cookies

For nebula the problem happens in tag `nebula-resources`, where it fetches the locales-file. This tag somehow needs to be extended so it can be configured whether the Session-ID should be sent along.

**Comment by rowe42** [comment]
My suggestion is as follows:

- Add boolean parameter sendCookies to nebula-resources, setting it to false by default
```
...
sendCookies: {
        type: Boolean,
        value: false
} 
...  
```

In [fetchResources]  check it and add the necessary params if true:
```
    [fetchResources](file, path) {
      if (!(file && path)) return

      if (!/\/$/ig.test(path)) path = path + '/'
      if (!/.json$/ig.test(file)) file = file + '.json'
      const url = this.resolveUrl(path + file)

      //HERE COMES THE NEW STUFF
      var params = {};
      if (this.sendCookies) {
           params = { credentials: 'same-origin' };
      }

      //AND HERE
      fetch(url, params).then((response) => {
        return response.json()
      }).then((resources) => {
        this._setResources(resources)
        this[fire]('loaded', resources)
      }).catch((error) => {
        this[fire]('error', error)
      })
    }
```

If have added this suggestion as pull request #2

**Comment by chrismbeckett** [comment]
Thanks for the pull request. I have merged the request and tagged a new patch release version.
